export const GET_TODO_DATA = 'GET_TODO_DATA';
export const ADD_ITEM_TODO = 'ADD_ITEM_TODO';
export const EDIT_TODO_ITEM = 'EDIT_TODO_ITEM';
export const DELETE_TODO_ITEM = 'DELETE_TODO_ITEM';
export const EDIT_TODO_ITEM_TEXT = 'EDIT_TODO_ITEM_TEXT';